### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [grafele/PullToReach#5]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by grafele** [comment]
Hi Mansya! You are more than welcome to give it a try. Thanks for your help!

**Comment by mansya** [comment]
HI, sir, I have designed it. How ? do you like it ? if yes please tell me which one you like.
![PullToReach](https://user-images.githubusercontent.com/33461607/59372468-c5bf9a00-8d71-11e9-8bf0-282705908584.png)
this is a merger between the letter P and the PULL icon. the letter P is taken from the first letter of the word PULL. while the arrow in it means the attraction that occurred in this project.

**Comment by mansya** [comment]
hi sir. how about this offer. don't you want to continue?

**Comment by grafele** [comment]
Hi Mansya. Thanks for your work. We unfortunately don't think we will add this icon to our repository. After thinking about it we came to the conclusion that a logo for this repository doesn't add a lot of value. Thanks for your work!
